//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_COMPLETIONEVENTOCCURRENCECOMPLETIONEVENTOCCURRENCEIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_COMPLETIONEVENTOCCURRENCECOMPLETIONEVENTOCCURRENCEIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../CompletionEventOccurrence.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class CompletionEventOccurrenceImpl :virtual public ecore::EObjectImpl,
virtual public CompletionEventOccurrence 
	{
		public: 
			CompletionEventOccurrenceImpl(const CompletionEventOccurrenceImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			CompletionEventOccurrenceImpl& operator=(CompletionEventOccurrenceImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			CompletionEventOccurrenceImpl();
			virtual std::shared_ptr<CompletionEventOccurrence> getThisCompletionEventOccurrencePtr() const;
			virtual void setThisCompletionEventOccurrencePtr(std::weak_ptr<CompletionEventOccurrence> thisCompletionEventOccurrencePtr);



		public:
			//destructor
			virtual ~CompletionEventOccurrenceImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getStateActivation() const ;
			
			/*!
			 */
			virtual void setStateActivation(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _stateActivation_stateActivation) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<CompletionEventOccurrence> m_thisCompletionEventOccurrencePtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_COMPLETIONEVENTOCCURRENCECOMPLETIONEVENTOCCURRENCEIMPL_HPP */
