//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCEDEFERREDEVENTOCCURRENCEIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCEDEFERREDEVENTOCCURRENCEIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../DeferredEventOccurrence.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"
#include "fUML/impl/EventOccurrenceImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class DeferredEventOccurrenceImpl :virtual public fUML::EventOccurrenceImpl, virtual public DeferredEventOccurrence 
	{
		public: 
			DeferredEventOccurrenceImpl(const DeferredEventOccurrenceImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			DeferredEventOccurrenceImpl& operator=(DeferredEventOccurrenceImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			DeferredEventOccurrenceImpl();
			virtual std::shared_ptr<DeferredEventOccurrence> getThisDeferredEventOccurrencePtr() const;
			virtual void setThisDeferredEventOccurrencePtr(std::weak_ptr<DeferredEventOccurrence> thisDeferredEventOccurrencePtr);



		public:
			//destructor
			virtual ~DeferredEventOccurrenceImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getConstrainingStateActivation() const ;
			
			/*!
			 */
			virtual void setConstrainingStateActivation(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _constrainingStateActivation_constrainingStateActivation) ;
			/*!
			 */
			virtual std::shared_ptr<fUML::EventOccurrence > getDeferredEventOccurrence() const ;
			
			/*!
			 */
			virtual void setDeferredEventOccurrence(std::shared_ptr<fUML::EventOccurrence> _deferredEventOccurrence_deferredEventOccurrence) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<DeferredEventOccurrence> m_thisDeferredEventOccurrencePtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCEDEFERREDEVENTOCCURRENCEIMPL_HPP */
