//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECTACTIVATIONDOACTIVITYCONTEXTOBJECTACTIVATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECTACTIVATIONDOACTIVITYCONTEXTOBJECTACTIVATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../DoActivityContextObjectActivation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class DoActivityContextObjectActivationImpl :virtual public ecore::EObjectImpl,
virtual public DoActivityContextObjectActivation 
	{
		public: 
			DoActivityContextObjectActivationImpl(const DoActivityContextObjectActivationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			DoActivityContextObjectActivationImpl& operator=(DoActivityContextObjectActivationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			DoActivityContextObjectActivationImpl();
			virtual std::shared_ptr<DoActivityContextObjectActivation> getThisDoActivityContextObjectActivationPtr() const;
			virtual void setThisDoActivityContextObjectActivationPtr(std::weak_ptr<DoActivityContextObjectActivation> thisDoActivityContextObjectActivationPtr);



		public:
			//destructor
			virtual ~DoActivityContextObjectActivationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void dispatchNextEvent() ;
			
			/*!
			 */ 
			virtual void startBehavior(std::shared_ptr<uml::Class>  classifier,std::shared_ptr<Bag<fUML::ParameterValue> >  inputs) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<DoActivityContextObjectActivation> m_thisDoActivityContextObjectActivationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECTACTIVATIONDOACTIVITYCONTEXTOBJECTACTIVATIONIMPL_HPP */
