//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTERDOACTIVITYEXECUTIONEVENTACCEPTERIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTERDOACTIVITYEXECUTIONEVENTACCEPTERIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../DoActivityExecutionEventAccepter.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class DoActivityExecutionEventAccepterImpl :virtual public ecore::EObjectImpl,
virtual public DoActivityExecutionEventAccepter 
	{
		public: 
			DoActivityExecutionEventAccepterImpl(const DoActivityExecutionEventAccepterImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			DoActivityExecutionEventAccepterImpl& operator=(DoActivityExecutionEventAccepterImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			DoActivityExecutionEventAccepterImpl();
			virtual std::shared_ptr<DoActivityExecutionEventAccepter> getThisDoActivityExecutionEventAccepterPtr() const;
			virtual void setThisDoActivityExecutionEventAccepterPtr(std::weak_ptr<DoActivityExecutionEventAccepter> thisDoActivityExecutionEventAccepterPtr);



		public:
			//destructor
			virtual ~DoActivityExecutionEventAccepterImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void accept(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			/*!
			 */ 
			virtual bool match(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject > getContext() const ;
			
			/*!
			 */
			virtual void setContext(std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject> _context_context) ;
			/*!
			 */
			virtual std::shared_ptr<fUML::EventAccepter > getEncapsulatedAccepter() const ;
			
			/*!
			 */
			virtual void setEncapsulatedAccepter(std::shared_ptr<fUML::EventAccepter> _encapsulatedAccepter_encapsulatedAccepter) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<DoActivityExecutionEventAccepter> m_thisDoActivityExecutionEventAccepterPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTERDOACTIVITYEXECUTIONEVENTACCEPTERIMPL_HPP */
