//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_FORKPSEUDOSTATEACTIVATIONFORKPSEUDOSTATEACTIVATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_FORKPSEUDOSTATEACTIVATIONFORKPSEUDOSTATEACTIVATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../ForkPseudostateActivation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"
#include "PSSM/Semantics/StateMachines/impl/PseudostateActivationImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class ForkPseudostateActivationImpl :virtual public PseudostateActivationImpl, virtual public ForkPseudostateActivation 
	{
		public: 
			ForkPseudostateActivationImpl(const ForkPseudostateActivationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			ForkPseudostateActivationImpl& operator=(ForkPseudostateActivationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			ForkPseudostateActivationImpl();
			virtual std::shared_ptr<ForkPseudostateActivation> getThisForkPseudostateActivationPtr() const;
			virtual void setThisForkPseudostateActivationPtr(std::weak_ptr<ForkPseudostateActivation> thisForkPseudostateActivationPtr);



		public:
			//destructor
			virtual ~ForkPseudostateActivationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual bool _canPropagateExecution(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence,std::shared_ptr<PSSM::Semantics::StateMachines::RegionActivation>  leastCommonAncestor) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<ForkPseudostateActivation> m_thisForkPseudostateActivationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_FORKPSEUDOSTATEACTIVATIONFORKPSEUDOSTATEACTIVATIONIMPL_HPP */
