//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_LOCALTRANSITIONACTIVATIONLOCALTRANSITIONACTIVATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_LOCALTRANSITIONACTIVATIONLOCALTRANSITIONACTIVATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../LocalTransitionActivation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"
#include "PSSM/Semantics/StateMachines/impl/TransitionActivationImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class LocalTransitionActivationImpl :virtual public TransitionActivationImpl, virtual public LocalTransitionActivation 
	{
		public: 
			LocalTransitionActivationImpl(const LocalTransitionActivationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			LocalTransitionActivationImpl& operator=(LocalTransitionActivationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			LocalTransitionActivationImpl();
			virtual std::shared_ptr<LocalTransitionActivation> getThisLocalTransitionActivationPtr() const;
			virtual void setThisLocalTransitionActivationPtr(std::weak_ptr<LocalTransitionActivation> thisLocalTransitionActivationPtr);



		public:
			//destructor
			virtual ~LocalTransitionActivationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> getContainingState() ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<LocalTransitionActivation> m_thisLocalTransitionActivationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_LOCALTRANSITIONACTIVATIONLOCALTRANSITIONACTIVATIONIMPL_HPP */
