//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATIONREGIONACTIVATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATIONREGIONACTIVATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../RegionActivation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"
#include "PSSM/Semantics/StateMachines/impl/StateMachineSemanticVisitorImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class RegionActivationImpl :virtual public StateMachineSemanticVisitorImpl, virtual public RegionActivation 
	{
		public: 
			RegionActivationImpl(const RegionActivationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			RegionActivationImpl& operator=(RegionActivationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			RegionActivationImpl();
			virtual std::shared_ptr<RegionActivation> getThisRegionActivationPtr() const;
			virtual void setThisRegionActivationPtr(std::weak_ptr<RegionActivation> thisRegionActivationPtr);



		public:
			//destructor
			virtual ~RegionActivationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual bool canPropagateExecution(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			/*!
			 */ 
			virtual void enter(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			/*!
			 */ 
			virtual void exit(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  exitingTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::InitialPseudostateActivation> getOrigin() ;
			
			/*!
			 */ 
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation> > getTransitionActivations() ;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation> getVertexActivation(std::shared_ptr<uml::Vertex>  vertex) ;
			
			
			
			/*!
			 */ 
			virtual bool isRedefined(std::shared_ptr<Bag<uml::Vertex> >  vertices,std::shared_ptr<uml::Vertex>  vertex) ;
			
			/*!
			 */ 
			virtual bool isRedefined(std::shared_ptr<Bag<uml::Transition> >  transitions,std::shared_ptr<uml::Transition>  transition) ;
			
			/*!
			 */ 
			virtual void terminate() ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			/*!
			 */ 
			virtual bool getIsCompleted() const ;
			
			/*!
			 */ 
			virtual void setIsCompleted (bool _isCompleted); 
			
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getHistory() const ;
			
			/*!
			 */
			virtual void setHistory(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _history_history) ;
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation>> getTransitionActivations() const ;
			
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation>> getVertexActivations() const ;
			
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<RegionActivation> m_thisRegionActivationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATIONREGIONACTIVATIONIMPL_HPP */
