//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP
#define PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../StateMachineConfiguration.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	class StateMachineConfigurationImpl :virtual public ecore::EObjectImpl,
virtual public StateMachineConfiguration 
	{
		public: 
			StateMachineConfigurationImpl(const StateMachineConfigurationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			StateMachineConfigurationImpl& operator=(StateMachineConfigurationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			StateMachineConfigurationImpl();
			virtual std::shared_ptr<StateMachineConfiguration> getThisStateMachineConfigurationPtr() const;
			virtual void setThisStateMachineConfigurationPtr(std::weak_ptr<StateMachineConfiguration> thisStateMachineConfigurationPtr);

			//Additional constructors for the containments back reference
			StateMachineConfigurationImpl(std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution > par_execution);




		public:
			//destructor
			virtual ~StateMachineConfigurationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual bool _register(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation>  stateActivation) ;
			
			/*!
			 */ 
			virtual bool add(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation) ;
			
			
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration> getRoot() ;
			
			/*!
			 */ 
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation> > getVertexActivationsAtLevel(int level) ;
			
			/*!
			 */ 
			virtual bool isActive(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation) ;
			
			/*!
			 */ 
			virtual bool isStable() ;
			
			/*!
			 */ 
			virtual bool remove(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  vertexActivation) ;
			
			/*!
			 */ 
			virtual bool unregister(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation>  stateActivation) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution > getExecution() const ;
			
			/*!
			 */
			virtual void setExecution(std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineExecution> _execution_execution) ;
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration > getRootConfiguration() const ;
			
			/*!
			 */
			virtual void setRootConfiguration(std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration> _rootConfiguration_rootConfiguration) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<StateMachineConfiguration> m_thisStateMachineConfigurationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_STATEMACHINECONFIGURATIONSTATEMACHINECONFIGURATIONIMPL_HPP */
