//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATIONSM_OPAQUEEXPRESSIONEVALUATIONIMPL_HPP
#define PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATIONSM_OPAQUEEXPRESSIONEVALUATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../SM_OpaqueExpressionEvaluation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::Values 
{
	class SM_OpaqueExpressionEvaluationImpl :virtual public ecore::EObjectImpl,
virtual public SM_OpaqueExpressionEvaluation 
	{
		public: 
			SM_OpaqueExpressionEvaluationImpl(const SM_OpaqueExpressionEvaluationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			SM_OpaqueExpressionEvaluationImpl& operator=(SM_OpaqueExpressionEvaluationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			SM_OpaqueExpressionEvaluationImpl();
			virtual std::shared_ptr<SM_OpaqueExpressionEvaluation> getThisSM_OpaqueExpressionEvaluationPtr() const;
			virtual void setThisSM_OpaqueExpressionEvaluationPtr(std::weak_ptr<SM_OpaqueExpressionEvaluation> thisSM_OpaqueExpressionEvaluationPtr);



		public:
			//destructor
			virtual ~SM_OpaqueExpressionEvaluationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual std::shared_ptr<Bag<fUML::Value> > executeExpressionBehavior() ;
			
			/*!
			 */ 
			virtual std::shared_ptr<fUML::ParameterValue> getParameterValue(std::shared_ptr<uml::Parameter>  parameter) ;
			
			/*!
			 */ 
			virtual void initialize(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) ;
			
			/*!
			 */ 
			virtual void setParameterValue(std::shared_ptr<fUML::ParameterValue>  parameterValue) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<fUML::Object > getContext() const ;
			
			/*!
			 */
			virtual void setContext(std::shared_ptr<fUML::Object> _context_context) ;
			/*!
			 */
			virtual std::shared_ptr<Bag<fUML::ParameterValue>> getParameterValues() const ;
			
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<SM_OpaqueExpressionEvaluation> m_thisSM_OpaqueExpressionEvaluationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATIONSM_OPAQUEEXPRESSIONEVALUATIONIMPL_HPP */
