//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSMPLUGINIMPL_HPP
#define PSSMPLUGINIMPL_HPP

#include "PSSM/PSSMPlugin.hpp"

namespace PSSM 
{
	class PSSMPluginImpl : virtual public PSSMPlugin 
	{
		public:
			PSSMPluginImpl();
			virtual ~PSSMPluginImpl();
		
			virtual std::string eclipseURI();
			virtual std::string eNAME();
			virtual std::string eNS_URI();
			virtual std::string eNS_PREFIX();
		
			virtual std::shared_ptr<ecore::EObject> create(const std::string& name);
			virtual std::shared_ptr<ecore::EFactory> getEFactory();
			virtual std::shared_ptr<ecore::EPackage> getEPackage();
	};
}
#endif /* end of include guard: PSSMPLUGINIMPL_HPP */
