//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSMFACTORYIMPL_HPP
#define PSSMFACTORYIMPL_HPP

#include "ecore/impl/EFactoryImpl.hpp"

#include "PSSM/PSSMFactory.hpp"

namespace PSSM 
{
}

namespace PSSM 
{
	class PSSMFactoryImpl : virtual public ecore::EFactoryImpl , virtual public PSSMFactory 
	{
		private:    
			PSSMFactoryImpl(PSSMFactoryImpl const&) = delete;
			PSSMFactoryImpl& operator=(PSSMFactoryImpl const&) = delete;

		protected:
			friend class PSSMFactory;
			// Constructor
			PSSMFactoryImpl();

		public:
			virtual ~PSSMFactoryImpl();
			virtual std::shared_ptr<ecore::EObject> create(std::string _className,  std::shared_ptr<ecore::EObject> container, const unsigned int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(const unsigned int classID,  std::shared_ptr<ecore::EObject> container = nullptr, const unsigned int referenceID = -1) const;
			virtual std::shared_ptr<ecore::EObject> create(std::shared_ptr<ecore::EClass> _class) const;
			virtual std::shared_ptr<ecore::EObject> create(std::shared_ptr<ecore::EClass> _class, std::shared_ptr<EObject> _container) const;
			virtual std::shared_ptr<ecore::EObject> create(std::string _className) const;

			//Creator functions
			virtual std::shared_ptr<PSSM::Semantics::CommonBehavior::CallEventExecution> createCallEventExecution() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::CommonBehavior::CallEventOccurrence> createCallEventOccurrence() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::ChoicePseudostateActivation> createChoicePseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::CompletionEventOccurrence> createCompletionEventOccurrence() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DeepHistoryPseudostateActivation> createDeepHistoryPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DeferredEventOccurrence> createDeferredEventOccurrence() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject> createDoActivityContextObject() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObjectActivation> createDoActivityContextObjectActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityExecutionEventAccepter> createDoActivityExecutionEventAccepter() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::EntryPointPseudostateActivation> createEntryPointPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::CommonBehavior::EventTriggeredExecution> createEventTriggeredExecution() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::ExitPointPseudostateActivation> createExitPointPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::ExternalTransitionActivation> createExternalTransitionActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::FinalStateActivation> createFinalStateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::ForkPseudostateActivation> createForkPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::InitialPseudostateActivation> createInitialPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::InternalTransitionActivation> createInternalTransitionActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::JoinPseudostateActivation> createJoinPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::JunctionPseudostateActivation> createJunctionPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::LocalTransitionActivation> createLocalTransitionActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::RegionActivation> createRegionActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::Loci::SM_ExecutionFactory> createSM_ExecutionFactory() const ;
			//Add containing object
			virtual std::shared_ptr<PSSM::Semantics::Loci::SM_ExecutionFactory> createSM_ExecutionFactory_in_Locus(std::weak_ptr<fUML::Locus > par_locus) const ;
			
			
			virtual std::shared_ptr<PSSM::Semantics::Loci::SM_Locus> createSM_Locus() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StructuredClassifiers::SM_Object> createSM_Object() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::CommonBehavior::SM_ObjectActivation> createSM_ObjectActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::Values::SM_OpaqueExpressionEvaluation> createSM_OpaqueExpressionEvaluation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::Actions::SM_ReadSelfActionActivation> createSM_ReadSelfActionActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StructuredClassifiers::SM_RedefinitionBasedDispatchStrategy> createSM_RedefinitionBasedDispatchStrategy() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::ShallowHistoryPseudostateActivation> createShallowHistoryPseudostateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> createStateActivation() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration> createStateConfiguration() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> createStateMachineConfiguration() const ;
			//Add containing object
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> createStateMachineConfiguration_in_Execution(std::weak_ptr<PSSM::Semantics::StateMachines::StateMachineExecution > par_execution) const ;
			
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineEventAccepter> createStateMachineEventAccepter() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineExecution> createStateMachineExecution() const ;
			
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::TerminatePseudostateActivation> createTerminatePseudostateActivation() const ;
			
			

			//Package
			virtual std::shared_ptr<PSSMPackage> getPSSMPackage() const;

		private:
			static PSSMFactory* create();
            std::map<std::string,unsigned int> m_idMap;
	};
}
#endif /* end of include guard: PSSMFACTORYIMPL_HPP */
