//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_COMMONBEHAVIOR_CALLEVENTOCCURRENCECALLEVENTOCCURRENCEIMPL_HPP
#define PSSM_SEMANTICS_COMMONBEHAVIOR_CALLEVENTOCCURRENCECALLEVENTOCCURRENCEIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../CallEventOccurrence.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::CommonBehavior 
{
	class CallEventOccurrenceImpl :virtual public ecore::EObjectImpl,
virtual public CallEventOccurrence 
	{
		public: 
			CallEventOccurrenceImpl(const CallEventOccurrenceImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			CallEventOccurrenceImpl& operator=(CallEventOccurrenceImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			CallEventOccurrenceImpl();
			virtual std::shared_ptr<CallEventOccurrence> getThisCallEventOccurrencePtr() const;
			virtual void setThisCallEventOccurrencePtr(std::weak_ptr<CallEventOccurrence> thisCallEventOccurrencePtr);



		public:
			//destructor
			virtual ~CallEventOccurrenceImpl();
			
			//*********************************
			// Operations
			//*********************************
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::CommonBehavior::CallEventExecution > getExecution() const ;
			
			/*!
			 */
			virtual void setExecution(std::shared_ptr<PSSM::Semantics::CommonBehavior::CallEventExecution> _execution_execution) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<CallEventOccurrence> m_thisCallEventOccurrencePtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_COMMONBEHAVIOR_CALLEVENTOCCURRENCECALLEVENTOCCURRENCEIMPL_HPP */
