//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_COMMONBEHAVIOR_EVENTTRIGGEREDEXECUTIONEVENTTRIGGEREDEXECUTIONIMPL_HPP
#define PSSM_SEMANTICS_COMMONBEHAVIOR_EVENTTRIGGEREDEXECUTIONEVENTTRIGGEREDEXECUTIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../EventTriggeredExecution.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::CommonBehavior 
{
	class EventTriggeredExecutionImpl :virtual public ecore::EObjectImpl,
virtual public EventTriggeredExecution 
	{
		public: 
			EventTriggeredExecutionImpl(const EventTriggeredExecutionImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			EventTriggeredExecutionImpl& operator=(EventTriggeredExecutionImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			EventTriggeredExecutionImpl();
			virtual std::shared_ptr<EventTriggeredExecution> getThisEventTriggeredExecutionPtr() const;
			virtual void setThisEventTriggeredExecutionPtr(std::weak_ptr<EventTriggeredExecution> thisEventTriggeredExecutionPtr);



		public:
			//destructor
			virtual ~EventTriggeredExecutionImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual std::shared_ptr<fUML::Value> copy() ;
			
			/*!
			 Execute the behavior given by the type of this execution. 
			The parameterValues for any input (in or in-out) parameters of the behavior should be set before the execution.
			The parameteValues for any output (in-out, out or return) parameters of the behavior will be set by the execution.
			 */ 
			virtual void execute() ;
			
			/*!
			 */ 
			virtual void finalize() ;
			
			/*!
			 */ 
			virtual void initialize() ;
			
			/*!
			 Create a new execution with no behavior or parameterValues.
			 */ 
			virtual std::shared_ptr<fUML::Value> new_() ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<fUML::EventOccurrence > getTriggeringEventOccurrence() const ;
			
			/*!
			 */
			virtual void setTriggeringEventOccurrence(std::shared_ptr<fUML::EventOccurrence> _triggeringEventOccurrence_triggeringEventOccurrence) ;
			/*!
			 */
			virtual std::shared_ptr<fUML::EventOccurrence > getWrappedExecution() const ;
			
			/*!
			 */
			virtual void setWrappedExecution(std::shared_ptr<fUML::EventOccurrence> _wrappedExecution_wrappedExecution) ;
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<EventTriggeredExecution> m_thisEventTriggeredExecutionPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_COMMONBEHAVIOR_EVENTTRIGGEREDEXECUTIONEVENTTRIGGEREDEXECUTIONIMPL_HPP */
