//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_ACTIONS_SM_READSELFACTIONACTIVATIONSM_READSELFACTIONACTIVATIONIMPL_HPP
#define PSSM_SEMANTICS_ACTIONS_SM_READSELFACTIONACTIVATIONSM_READSELFACTIONACTIVATIONIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../SM_ReadSelfActionActivation.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::Actions 
{
	class SM_ReadSelfActionActivationImpl :virtual public ecore::EObjectImpl,
virtual public SM_ReadSelfActionActivation 
	{
		public: 
			SM_ReadSelfActionActivationImpl(const SM_ReadSelfActionActivationImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			SM_ReadSelfActionActivationImpl& operator=(SM_ReadSelfActionActivationImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			SM_ReadSelfActionActivationImpl();
			virtual std::shared_ptr<SM_ReadSelfActionActivation> getThisSM_ReadSelfActionActivationPtr() const;
			virtual void setThisSM_ReadSelfActionActivationPtr(std::weak_ptr<SM_ReadSelfActionActivation> thisSM_ReadSelfActionActivationPtr);



		public:
			//destructor
			virtual ~SM_ReadSelfActionActivationImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual std::shared_ptr<fUML::Object> getExecutionContext() ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<SM_ReadSelfActionActivation> m_thisSM_ReadSelfActionActivationPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_ACTIONS_SM_READSELFACTIONACTIVATIONSM_READSELFACTIONACTIVATIONIMPL_HPP */
