//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STRUCTUREDCLASSIFIERS_SM_OBJECTSM_OBJECTIMPL_HPP
#define PSSM_SEMANTICS_STRUCTUREDCLASSIFIERS_SM_OBJECTSM_OBJECTIMPL_HPP

//*********************************
// generated Includes

//Model includes
#include "../SM_Object.hpp"

#include "PSSM/impl/PSSMFactoryImpl.hpp"

#include "ecore/impl/EObjectImpl.hpp"

//*********************************
namespace PSSM::Semantics::StructuredClassifiers 
{
	class SM_ObjectImpl :virtual public ecore::EObjectImpl,
virtual public SM_Object 
	{
		public: 
			SM_ObjectImpl(const SM_ObjectImpl & obj);
			virtual std::shared_ptr<ecore::EObject> copy() const;

		private:    
			SM_ObjectImpl& operator=(SM_ObjectImpl const&) = delete;

		protected:
			friend class PSSM::PSSMFactoryImpl;
			SM_ObjectImpl();
			virtual std::shared_ptr<SM_Object> getThisSM_ObjectPtr() const;
			virtual void setThisSM_ObjectPtr(std::weak_ptr<SM_Object> thisSM_ObjectPtr);



		public:
			//destructor
			virtual ~SM_ObjectImpl();
			
			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void destroy() ;
			
			/*!
			 */ 
			virtual void startBehavior(std::shared_ptr<uml::Class>  classifier,std::shared_ptr<Bag<fUML::ParameterValue> >  inputs) ;
			
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			
			//*********************************
			// Reference
			//*********************************
							
			
			//*********************************
			// Union Getter
			//*********************************
			 
			 
			//*********************************
			// Structural Feature Getter/Setter
			//*********************************

			virtual std::shared_ptr<ecore::EObject> eContainer() const ; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) ;
			virtual void loadAttributes(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::map<std::string, std::string> attr_list);
			virtual void loadNode(std::string nodeName, std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler, std::shared_ptr<PSSM::PSSMFactory> modelFactory);
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) ;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const ;
			virtual void saveContent(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const;
			

		protected:
			virtual std::shared_ptr<ecore::EClass> eStaticClass() const;
			virtual Any eGet(int featureID, bool resolve, bool coreType) const ;
			virtual bool internalEIsSet(int featureID) const ;
			virtual bool eSet(int featureID, Any newValue) ;

		private:
			std::weak_ptr<SM_Object> m_thisSM_ObjectPtr;
	};
}
#endif /* end of include guard: PSSM_SEMANTICS_STRUCTUREDCLASSIFIERS_SM_OBJECTSM_OBJECTIMPL_HPP */
