//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSMPACKAGE_HPP
#define PSSMPACKAGE_HPP

#include "ecore/EPackage.hpp"

namespace ecore 
{
	class EAnnotation;
	class EAttribute;
	class EClass;
	class EDataType;
	class EEnum;
	class EEnumLiteral;
	class EGenericType;
	class EOperation;
	class EPackage;
	class EParameter;
	class EReference;
	class EStringToStringMapEntry;
}

namespace PSSM 
{
	/*!
	The Metamodel Package for the PSSM metamodel. This package is used to enable the reflection of model elements. It contains all model elements
	which were described in an ecore file.
	*/
	/*!
	 */
	class PSSMPackage : virtual public ecore::EPackage 
	{
		private:    
			PSSMPackage(PSSMPackage const&) = delete;
			PSSMPackage& operator=(PSSMPackage const&) = delete;

		protected:
			PSSMPackage(){}

		public:
			//static variables
			static const std::string eNAME;
			static const std::string eNS_URI;
			static const std::string eNS_PREFIX;

			// Begin Class CallEventExecution
			//Class and Feature IDs 
			static const unsigned int CALLEVENTEXECUTION_ECLASS = 1;
			static const unsigned int CALLEVENTEXECUTION_ECLASS_FEATURE_COUNT = 4;
			static const unsigned int CALLEVENTEXECUTION_ECLASS_OPERATION_COUNT = 7;
			static const int CALLEVENTEXECUTION_EATTRIBUTE_CALLERSUSPENDED = 100;
			
			static const int CALLEVENTEXECUTION_EREFERENCE_BEHAVIOR = 103;
			static const int CALLEVENTEXECUTION_EREFERENCE_CALLERCONTEXT = 101;
			static const int CALLEVENTEXECUTION_EREFERENCE_OPERATION = 102;
			
			static const int CALLEVENTEXECUTION_EOPERATION__SEND_CALLEVENTOCCURRENCE = 104;
			static const int CALLEVENTEXECUTION_EOPERATION__SUSPEND = 105;
			static const int CALLEVENTEXECUTION_EOPERATION_EXECUTE = 106;
			static const int CALLEVENTEXECUTION_EOPERATION_GETBEHAVIOR = 107;
			static const int CALLEVENTEXECUTION_EOPERATION_GETINPUTPARAMETERVALUES = 110;
			static const int CALLEVENTEXECUTION_EOPERATION_NEW_ = 108;
			static const int CALLEVENTEXECUTION_EOPERATION_RELEASECALLER = 109;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCallEventExecution_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getCallEventExecution_EAttribute_callerSuspended() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getCallEventExecution_EReference_behavior() const = 0;
			virtual std::shared_ptr<ecore::EReference> getCallEventExecution_EReference_callerContext() const = 0;
			virtual std::shared_ptr<ecore::EReference> getCallEventExecution_EReference_operation() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation__send_CallEventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation__suspend() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation_execute() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation_getBehavior() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation_getInputParameterValues() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation_new_() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getCallEventExecution_EOperation_releaseCaller() const = 0;
			
			// End Class CallEventExecution


			// Begin Class CallEventOccurrence
			//Class and Feature IDs 
			static const unsigned int CALLEVENTOCCURRENCE_ECLASS = 2;
			static const unsigned int CALLEVENTOCCURRENCE_ECLASS_FEATURE_COUNT = 1;
			static const unsigned int CALLEVENTOCCURRENCE_ECLASS_OPERATION_COUNT = 0;
			
			static const int CALLEVENTOCCURRENCE_EREFERENCE_EXECUTION = 200;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCallEventOccurrence_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getCallEventOccurrence_EReference_execution() const = 0;
			
			
			// End Class CallEventOccurrence


			// Begin Class ChoicePseudostateActivation
			//Class and Feature IDs 
			static const unsigned int CHOICEPSEUDOSTATEACTIVATION_ECLASS = 3;
			static const unsigned int CHOICEPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int CHOICEPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getChoicePseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class ChoicePseudostateActivation


			// Begin Class CompletionEventOccurrence
			//Class and Feature IDs 
			static const unsigned int COMPLETIONEVENTOCCURRENCE_ECLASS = 4;
			static const unsigned int COMPLETIONEVENTOCCURRENCE_ECLASS_FEATURE_COUNT = 1;
			static const unsigned int COMPLETIONEVENTOCCURRENCE_ECLASS_OPERATION_COUNT = 0;
			
			static const int COMPLETIONEVENTOCCURRENCE_EREFERENCE_STATEACTIVATION = 400;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getCompletionEventOccurrence_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getCompletionEventOccurrence_EReference_stateActivation() const = 0;
			
			
			// End Class CompletionEventOccurrence


			// Begin Class ConditionalPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int CONDITIONALPSEUDOSTATEACTIVATION_ECLASS = 5;
			static const unsigned int CONDITIONALPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int CONDITIONALPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			static const int CONDITIONALPSEUDOSTATEACTIVATION_EOPERATION_ISELSETRANSITION_TRANSITIONACTIVATION = 541;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getConditionalPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getConditionalPseudostateActivation_EOperation_isElseTransition_TransitionActivation() const = 0;
			
			// End Class ConditionalPseudostateActivation


			// Begin Class ConnectionPointActivation
			//Class and Feature IDs 
			static const unsigned int CONNECTIONPOINTACTIVATION_ECLASS = 6;
			static const unsigned int CONNECTIONPOINTACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int CONNECTIONPOINTACTIVATION_ECLASS_OPERATION_COUNT = 35;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getConnectionPointActivation_EClass() const = 0;
			
			
			
			
			// End Class ConnectionPointActivation


			// Begin Class DeepHistoryPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int DEEPHISTORYPSEUDOSTATEACTIVATION_ECLASS = 7;
			static const unsigned int DEEPHISTORYPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int DEEPHISTORYPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 39;
			
			
			static const int DEEPHISTORYPSEUDOSTATEACTIVATION_EOPERATION_CANRESTORE_STATEACTIVATION = 744;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getDeepHistoryPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getDeepHistoryPseudostateActivation_EOperation_canRestore_StateActivation() const = 0;
			
			// End Class DeepHistoryPseudostateActivation


			// Begin Class DeferredEventOccurrence
			//Class and Feature IDs 
			static const unsigned int DEFERREDEVENTOCCURRENCE_ECLASS = 8;
			static const unsigned int DEFERREDEVENTOCCURRENCE_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int DEFERREDEVENTOCCURRENCE_ECLASS_OPERATION_COUNT = 0;
			
			static const int DEFERREDEVENTOCCURRENCE_EREFERENCE_CONSTRAININGSTATEACTIVATION = 800;
			static const int DEFERREDEVENTOCCURRENCE_EREFERENCE_DEFERREDEVENTOCCURRENCE = 801;
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getDeferredEventOccurrence_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getDeferredEventOccurrence_EReference_constrainingStateActivation() const = 0;
			virtual std::shared_ptr<ecore::EReference> getDeferredEventOccurrence_EReference_deferredEventOccurrence() const = 0;
			
			
			// End Class DeferredEventOccurrence


			// Begin Class DoActivityContextObject
			//Class and Feature IDs 
			static const unsigned int DOACTIVITYCONTEXTOBJECT_ECLASS = 9;
			static const unsigned int DOACTIVITYCONTEXTOBJECT_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int DOACTIVITYCONTEXTOBJECT_ECLASS_OPERATION_COUNT = 10;
			
			static const int DOACTIVITYCONTEXTOBJECT_EREFERENCE_CONTEXT = 900;
			static const int DOACTIVITYCONTEXTOBJECT_EREFERENCE_OWNER = 901;
			
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION__REGISTER_EVENTACCEPTER = 907;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_DESTROY = 908;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_DISPATCH_OPERATION = 904;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_GETFEATUREVALUE_STRUCTURALFEATURE = 902;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_INITIALIZE_OBJECT = 910;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_SEND_EVENTOCCURRENCE = 905;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_SETFEATUREVALUE_STRUCTURALFEATURE_INTEGER = 903;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_STARTBEHAVIOR_CLASS_PARAMETERVALUE = 911;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_UNREGISTER_EVENTACCEPTER = 906;
			static const int DOACTIVITYCONTEXTOBJECT_EOPERATION_UNREGISTERFROMCONTEXT_EVENTACCEPTER = 909;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getDoActivityContextObject_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getDoActivityContextObject_EReference_context() const = 0;
			virtual std::shared_ptr<ecore::EReference> getDoActivityContextObject_EReference_owner() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation__register_EventAccepter() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_destroy() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_dispatch_Operation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_getFeatureValue_StructuralFeature() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_initialize_Object() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_send_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_setFeatureValue_StructuralFeature_Integer() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_startBehavior_Class_ParameterValue() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_unregister_EventAccepter() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObject_EOperation_unregisterFromContext_EventAccepter() const = 0;
			
			// End Class DoActivityContextObject


			// Begin Class DoActivityContextObjectActivation
			//Class and Feature IDs 
			static const unsigned int DOACTIVITYCONTEXTOBJECTACTIVATION_ECLASS = 10;
			static const unsigned int DOACTIVITYCONTEXTOBJECTACTIVATION_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int DOACTIVITYCONTEXTOBJECTACTIVATION_ECLASS_OPERATION_COUNT = 2;
			
			
			static const int DOACTIVITYCONTEXTOBJECTACTIVATION_EOPERATION_DISPATCHNEXTEVENT = 1000;
			static const int DOACTIVITYCONTEXTOBJECTACTIVATION_EOPERATION_STARTBEHAVIOR_CLASS_PARAMETERVALUE = 1001;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getDoActivityContextObjectActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObjectActivation_EOperation_dispatchNextEvent() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityContextObjectActivation_EOperation_startBehavior_Class_ParameterValue() const = 0;
			
			// End Class DoActivityContextObjectActivation


			// Begin Class DoActivityExecutionEventAccepter
			//Class and Feature IDs 
			static const unsigned int DOACTIVITYEXECUTIONEVENTACCEPTER_ECLASS = 11;
			static const unsigned int DOACTIVITYEXECUTIONEVENTACCEPTER_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int DOACTIVITYEXECUTIONEVENTACCEPTER_ECLASS_OPERATION_COUNT = 2;
			
			static const int DOACTIVITYEXECUTIONEVENTACCEPTER_EREFERENCE_CONTEXT = 1100;
			static const int DOACTIVITYEXECUTIONEVENTACCEPTER_EREFERENCE_ENCAPSULATEDACCEPTER = 1101;
			
			static const int DOACTIVITYEXECUTIONEVENTACCEPTER_EOPERATION_ACCEPT_EVENTOCCURRENCE = 1103;
			static const int DOACTIVITYEXECUTIONEVENTACCEPTER_EOPERATION_MATCH_EVENTOCCURRENCE = 1102;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getDoActivityExecutionEventAccepter_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getDoActivityExecutionEventAccepter_EReference_context() const = 0;
			virtual std::shared_ptr<ecore::EReference> getDoActivityExecutionEventAccepter_EReference_encapsulatedAccepter() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getDoActivityExecutionEventAccepter_EOperation_accept_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getDoActivityExecutionEventAccepter_EOperation_match_EventOccurrence() const = 0;
			
			// End Class DoActivityExecutionEventAccepter


			// Begin Class EntryPointPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int ENTRYPOINTPSEUDOSTATEACTIVATION_ECLASS = 12;
			static const unsigned int ENTRYPOINTPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int ENTRYPOINTPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			static const int ENTRYPOINTPSEUDOSTATEACTIVATION_EOPERATION__ENTER_TRANSITIONACTIVATION_REGIONACTIVATION = 1241;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getEntryPointPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getEntryPointPseudostateActivation_EOperation__enter_TransitionActivation_RegionActivation() const = 0;
			
			// End Class EntryPointPseudostateActivation


			// Begin Class EventTriggeredExecution
			//Class and Feature IDs 
			static const unsigned int EVENTTRIGGEREDEXECUTION_ECLASS = 13;
			static const unsigned int EVENTTRIGGEREDEXECUTION_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int EVENTTRIGGEREDEXECUTION_ECLASS_OPERATION_COUNT = 5;
			
			static const int EVENTTRIGGEREDEXECUTION_EREFERENCE_TRIGGERINGEVENTOCCURRENCE = 1301;
			static const int EVENTTRIGGEREDEXECUTION_EREFERENCE_WRAPPEDEXECUTION = 1300;
			
			static const int EVENTTRIGGEREDEXECUTION_EOPERATION_COPY = 1305;
			static const int EVENTTRIGGEREDEXECUTION_EOPERATION_EXECUTE = 1303;
			static const int EVENTTRIGGEREDEXECUTION_EOPERATION_FINALIZE = 1302;
			static const int EVENTTRIGGEREDEXECUTION_EOPERATION_INITIALIZE = 1304;
			static const int EVENTTRIGGEREDEXECUTION_EOPERATION_NEW_ = 1306;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getEventTriggeredExecution_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getEventTriggeredExecution_EReference_triggeringEventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EReference> getEventTriggeredExecution_EReference_wrappedExecution() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getEventTriggeredExecution_EOperation_copy() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getEventTriggeredExecution_EOperation_execute() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getEventTriggeredExecution_EOperation_finalize() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getEventTriggeredExecution_EOperation_initialize() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getEventTriggeredExecution_EOperation_new_() const = 0;
			
			// End Class EventTriggeredExecution


			// Begin Class ExitPointPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int EXITPOINTPSEUDOSTATEACTIVATION_ECLASS = 14;
			static const unsigned int EXITPOINTPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int EXITPOINTPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 35;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getExitPointPseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class ExitPointPseudostateActivation


			// Begin Class ExternalTransitionActivation
			//Class and Feature IDs 
			static const unsigned int EXTERNALTRANSITIONACTIVATION_ECLASS = 15;
			static const unsigned int EXTERNALTRANSITIONACTIVATION_ECLASS_FEATURE_COUNT = 9;
			static const unsigned int EXTERNALTRANSITIONACTIVATION_ECLASS_OPERATION_COUNT = 32;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getExternalTransitionActivation_EClass() const = 0;
			
			
			
			
			// End Class ExternalTransitionActivation


			// Begin Class FinalStateActivation
			//Class and Feature IDs 
			static const unsigned int FINALSTATEACTIVATION_ECLASS = 16;
			static const unsigned int FINALSTATEACTIVATION_ECLASS_FEATURE_COUNT = 11;
			static const unsigned int FINALSTATEACTIVATION_ECLASS_OPERATION_COUNT = 50;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getFinalStateActivation_EClass() const = 0;
			
			
			
			
			// End Class FinalStateActivation


			// Begin Class ForkPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int FORKPSEUDOSTATEACTIVATION_ECLASS = 17;
			static const unsigned int FORKPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int FORKPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			static const int FORKPSEUDOSTATEACTIVATION_EOPERATION__CANPROPAGATEEXECUTION_TRANSITIONACTIVATION_REGIONACTIVATION = 1741;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getForkPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getForkPseudostateActivation_EOperation__canPropagateExecution_TransitionActivation_RegionActivation() const = 0;
			
			// End Class ForkPseudostateActivation


			// Begin Class HistoryPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int HISTORYPSEUDOSTATEACTIVATION_ECLASS = 18;
			static const unsigned int HISTORYPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int HISTORYPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 38;
			
			
			static const int HISTORYPSEUDOSTATEACTIVATION_EOPERATION_HASDEFAULTTRANSITION = 1841;
			static const int HISTORYPSEUDOSTATEACTIVATION_EOPERATION_RESTORE_STATEACTIVATION_EVENTOCCURRENCE = 1842;
			static const int HISTORYPSEUDOSTATEACTIVATION_EOPERATION_RESTORE_REGIONACTIVATION_EVENTOCCURRENCE = 1843;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getHistoryPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getHistoryPseudostateActivation_EOperation_hasDefaultTransition() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getHistoryPseudostateActivation_EOperation_restore_StateActivation_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getHistoryPseudostateActivation_EOperation_restore_RegionActivation_EventOccurrence() const = 0;
			
			// End Class HistoryPseudostateActivation


			// Begin Class InitialPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int INITIALPSEUDOSTATEACTIVATION_ECLASS = 19;
			static const unsigned int INITIALPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int INITIALPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 35;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getInitialPseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class InitialPseudostateActivation


			// Begin Class InternalTransitionActivation
			//Class and Feature IDs 
			static const unsigned int INTERNALTRANSITIONACTIVATION_ECLASS = 20;
			static const unsigned int INTERNALTRANSITIONACTIVATION_ECLASS_FEATURE_COUNT = 9;
			static const unsigned int INTERNALTRANSITIONACTIVATION_ECLASS_OPERATION_COUNT = 32;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getInternalTransitionActivation_EClass() const = 0;
			
			
			
			
			// End Class InternalTransitionActivation


			// Begin Class JoinPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int JOINPSEUDOSTATEACTIVATION_ECLASS = 21;
			static const unsigned int JOINPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int JOINPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			static const int JOINPSEUDOSTATEACTIVATION_EOPERATION__CANPROPAGATEEXECUTION_TRANSITIONACTIVATION_REGIONACTIVATION = 2141;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getJoinPseudostateActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getJoinPseudostateActivation_EOperation__canPropagateExecution_TransitionActivation_RegionActivation() const = 0;
			
			// End Class JoinPseudostateActivation


			// Begin Class JunctionPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int JUNCTIONPSEUDOSTATEACTIVATION_ECLASS = 22;
			static const unsigned int JUNCTIONPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int JUNCTIONPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 36;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getJunctionPseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class JunctionPseudostateActivation


			// Begin Class LocalTransitionActivation
			//Class and Feature IDs 
			static const unsigned int LOCALTRANSITIONACTIVATION_ECLASS = 23;
			static const unsigned int LOCALTRANSITIONACTIVATION_ECLASS_FEATURE_COUNT = 9;
			static const unsigned int LOCALTRANSITIONACTIVATION_ECLASS_OPERATION_COUNT = 33;
			
			
			static const int LOCALTRANSITIONACTIVATION_EOPERATION_GETCONTAININGSTATE = 2341;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getLocalTransitionActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getLocalTransitionActivation_EOperation_getContainingState() const = 0;
			
			// End Class LocalTransitionActivation


			// Begin Class PseudostateActivation
			//Class and Feature IDs 
			static const unsigned int PSEUDOSTATEACTIVATION_ECLASS = 24;
			static const unsigned int PSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int PSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 35;
			
			static const int PSEUDOSTATEACTIVATION_EREFERENCE_FIREABLETRANSITIONS = 2405;
			
			static const int PSEUDOSTATEACTIVATION_EOPERATION_EVALUATEALLGUARDS_EVENTOCCURRENCE = 2440;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getPseudostateActivation_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getPseudostateActivation_EReference_fireableTransitions() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getPseudostateActivation_EOperation_evaluateAllGuards_EventOccurrence() const = 0;
			
			// End Class PseudostateActivation


			// Begin Class RegionActivation
			//Class and Feature IDs 
			static const unsigned int REGIONACTIVATION_ECLASS = 25;
			static const unsigned int REGIONACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int REGIONACTIVATION_ECLASS_OPERATION_COUNT = 23;
			static const int REGIONACTIVATION_EATTRIBUTE_ISCOMPLETED = 2503;
			
			static const int REGIONACTIVATION_EREFERENCE_HISTORY = 2505;
			static const int REGIONACTIVATION_EREFERENCE_TRANSITIONACTIVATIONS = 2502;
			static const int REGIONACTIVATION_EREFERENCE_VERTEXACTIVATIONS = 2504;
			
			static const int REGIONACTIVATION_EOPERATION_CANPROPAGATEEXECUTION_TRANSITIONACTIVATION_EVENTOCCURRENCE = 2528;
			static const int REGIONACTIVATION_EOPERATION_ENTER_TRANSITIONACTIVATION_EVENTOCCURRENCE = 2526;
			static const int REGIONACTIVATION_EOPERATION_EXIT_TRANSITIONACTIVATION_EVENTOCCURRENCE = 2527;
			static const int REGIONACTIVATION_EOPERATION_GETORIGIN = 2520;
			static const int REGIONACTIVATION_EOPERATION_GETTRANSITIONACTIVATIONS = 2522;
			static const int REGIONACTIVATION_EOPERATION_GETVERTEXACTIVATION_VERTEX = 2523;
			static const int REGIONACTIVATION_EOPERATION_GETVERTEXACTIVATIONS = 2521;
			static const int REGIONACTIVATION_EOPERATION_ISREDEFINED_VERTEX_VERTEX = 2524;
			static const int REGIONACTIVATION_EOPERATION_ISREDEFINED_TRANSITION_TRANSITION = 2525;
			static const int REGIONACTIVATION_EOPERATION_TERMINATE = 2519;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getRegionActivation_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getRegionActivation_EAttribute_isCompleted() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getRegionActivation_EReference_history() const = 0;
			virtual std::shared_ptr<ecore::EReference> getRegionActivation_EReference_transitionActivations() const = 0;
			virtual std::shared_ptr<ecore::EReference> getRegionActivation_EReference_vertexActivations() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_canPropagateExecution_TransitionActivation_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_enter_TransitionActivation_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_exit_TransitionActivation_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_getOrigin() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_getTransitionActivations() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_getVertexActivation_Vertex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_getVertexActivations() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_isRedefined_Vertex_Vertex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_isRedefined_Transition_Transition() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getRegionActivation_EOperation_terminate() const = 0;
			
			// End Class RegionActivation


			// Begin Class SM_ExecutionFactory
			//Class and Feature IDs 
			static const unsigned int SM_EXECUTIONFACTORY_ECLASS = 26;
			static const unsigned int SM_EXECUTIONFACTORY_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int SM_EXECUTIONFACTORY_ECLASS_OPERATION_COUNT = 1;
			
			
			static const int SM_EXECUTIONFACTORY_EOPERATION_INSTANTIATEVISITOR_ELEMENT = 2600;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_ExecutionFactory_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getSM_ExecutionFactory_EOperation_instantiateVisitor_Element() const = 0;
			
			// End Class SM_ExecutionFactory


			// Begin Class SM_Locus
			//Class and Feature IDs 
			static const unsigned int SM_LOCUS_ECLASS = 27;
			static const unsigned int SM_LOCUS_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int SM_LOCUS_ECLASS_OPERATION_COUNT = 1;
			
			
			static const int SM_LOCUS_EOPERATION_INSTANTIATE_CLASS = 2700;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_Locus_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getSM_Locus_EOperation_instantiate_Class() const = 0;
			
			// End Class SM_Locus


			// Begin Class SM_Object
			//Class and Feature IDs 
			static const unsigned int SM_OBJECT_ECLASS = 28;
			static const unsigned int SM_OBJECT_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int SM_OBJECT_ECLASS_OPERATION_COUNT = 2;
			
			
			static const int SM_OBJECT_EOPERATION_DESTROY = 2801;
			static const int SM_OBJECT_EOPERATION_STARTBEHAVIOR_CLASS_PARAMETERVALUE = 2800;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_Object_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getSM_Object_EOperation_destroy() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_Object_EOperation_startBehavior_Class_ParameterValue() const = 0;
			
			// End Class SM_Object


			// Begin Class SM_ObjectActivation
			//Class and Feature IDs 
			static const unsigned int SM_OBJECTACTIVATION_ECLASS = 29;
			static const unsigned int SM_OBJECTACTIVATION_ECLASS_FEATURE_COUNT = 1;
			static const unsigned int SM_OBJECTACTIVATION_ECLASS_OPERATION_COUNT = 6;
			
			static const int SM_OBJECTACTIVATION_EREFERENCE_DEFERREDEVENTPOOL = 2900;
			
			static const int SM_OBJECTACTIVATION_EOPERATION_GETDEFERREDEVENTINSERTIONINDEX = 2902;
			static const int SM_OBJECTACTIVATION_EOPERATION_GETNEXTCOMPLETIONEVENT = 2901;
			static const int SM_OBJECTACTIVATION_EOPERATION_GETNEXTEVENT = 2906;
			static const int SM_OBJECTACTIVATION_EOPERATION_REGISTERCOMPLETIONEVENT_STATEACTIVATION = 2903;
			static const int SM_OBJECTACTIVATION_EOPERATION_REGISTERDEFERREDEVENT_EVENTOCCURRENCE_STATEACTIVATION = 2905;
			static const int SM_OBJECTACTIVATION_EOPERATION_RELEASEDEFERREDEVENTS_STATEACTIVATION = 2904;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_ObjectActivation_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getSM_ObjectActivation_EReference_deferredEventPool() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_getDeferredEventInsertionIndex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_getNextCompletionEvent() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_getNextEvent() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_registerCompletionEvent_StateActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_registerDeferredEvent_EventOccurrence_StateActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_ObjectActivation_EOperation_releaseDeferredEvents_StateActivation() const = 0;
			
			// End Class SM_ObjectActivation


			// Begin Class SM_OpaqueExpressionEvaluation
			//Class and Feature IDs 
			static const unsigned int SM_OPAQUEEXPRESSIONEVALUATION_ECLASS = 30;
			static const unsigned int SM_OPAQUEEXPRESSIONEVALUATION_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int SM_OPAQUEEXPRESSIONEVALUATION_ECLASS_OPERATION_COUNT = 4;
			
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EREFERENCE_CONTEXT = 3000;
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EREFERENCE_PARAMETERVALUES = 3001;
			
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EOPERATION_EXECUTEEXPRESSIONBEHAVIOR = 3002;
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EOPERATION_GETPARAMETERVALUE_PARAMETER = 3004;
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EOPERATION_INITIALIZE_EVENTOCCURRENCE = 3003;
			static const int SM_OPAQUEEXPRESSIONEVALUATION_EOPERATION_SETPARAMETERVALUE_PARAMETERVALUE = 3005;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_OpaqueExpressionEvaluation_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getSM_OpaqueExpressionEvaluation_EReference_context() const = 0;
			virtual std::shared_ptr<ecore::EReference> getSM_OpaqueExpressionEvaluation_EReference_parameterValues() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getSM_OpaqueExpressionEvaluation_EOperation_executeExpressionBehavior() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_OpaqueExpressionEvaluation_EOperation_getParameterValue_Parameter() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_OpaqueExpressionEvaluation_EOperation_initialize_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_OpaqueExpressionEvaluation_EOperation_setParameterValue_ParameterValue() const = 0;
			
			// End Class SM_OpaqueExpressionEvaluation


			// Begin Class SM_ReadSelfActionActivation
			//Class and Feature IDs 
			static const unsigned int SM_READSELFACTIONACTIVATION_ECLASS = 31;
			static const unsigned int SM_READSELFACTIONACTIVATION_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int SM_READSELFACTIONACTIVATION_ECLASS_OPERATION_COUNT = 1;
			
			
			static const int SM_READSELFACTIONACTIVATION_EOPERATION_GETEXECUTIONCONTEXT = 3100;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_ReadSelfActionActivation_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getSM_ReadSelfActionActivation_EOperation_getExecutionContext() const = 0;
			
			// End Class SM_ReadSelfActionActivation


			// Begin Class SM_RedefinitionBasedDispatchStrategy
			//Class and Feature IDs 
			static const unsigned int SM_REDEFINITIONBASEDDISPATCHSTRATEGY_ECLASS = 32;
			static const unsigned int SM_REDEFINITIONBASEDDISPATCHSTRATEGY_ECLASS_FEATURE_COUNT = 0;
			static const unsigned int SM_REDEFINITIONBASEDDISPATCHSTRATEGY_ECLASS_OPERATION_COUNT = 2;
			
			
			static const int SM_REDEFINITIONBASEDDISPATCHSTRATEGY_EOPERATION_DISPATCH_OBJECT_OPERATION = 3201;
			static const int SM_REDEFINITIONBASEDDISPATCHSTRATEGY_EOPERATION_GETMETHOD_OBJECT_OPERATION = 3200;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getSM_RedefinitionBasedDispatchStrategy_EClass() const = 0;
			
			
			
			virtual std::shared_ptr<ecore::EOperation> getSM_RedefinitionBasedDispatchStrategy_EOperation_dispatch_Object_Operation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getSM_RedefinitionBasedDispatchStrategy_EOperation_getMethod_Object_Operation() const = 0;
			
			// End Class SM_RedefinitionBasedDispatchStrategy


			// Begin Class ShallowHistoryPseudostateActivation
			//Class and Feature IDs 
			static const unsigned int SHALLOWHISTORYPSEUDOSTATEACTIVATION_ECLASS = 33;
			static const unsigned int SHALLOWHISTORYPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int SHALLOWHISTORYPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 38;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getShallowHistoryPseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class ShallowHistoryPseudostateActivation


			// Begin Class StateActivation
			//Class and Feature IDs 
			static const unsigned int STATEACTIVATION_ECLASS = 34;
			static const unsigned int STATEACTIVATION_ECLASS_FEATURE_COUNT = 11;
			static const unsigned int STATEACTIVATION_ECLASS_OPERATION_COUNT = 50;
			static const int STATEACTIVATION_EATTRIBUTE_ISDOACTIVITYCOMPLETED = 3407;
			static const int STATEACTIVATION_EATTRIBUTE_ISENTRYCOMPLETED = 3408;
			static const int STATEACTIVATION_EATTRIBUTE_ISEXITCOMPLETED = 3409;
			
			static const int STATEACTIVATION_EREFERENCE_CONNECTIONPOINTACTIVATIONS = 3405;
			static const int STATEACTIVATION_EREFERENCE_DOACTIVITYCONTEXTOBJECT = 3410;
			static const int STATEACTIVATION_EREFERENCE_REGIONACTIVATIONS = 3406;
			
			static const int STATEACTIVATION_EOPERATION_CANDEFER_EVENTOCCURRENCE = 3452;
			static const int STATEACTIVATION_EOPERATION_DEFER_EVENTOCCURRENCE = 3448;
			static const int STATEACTIVATION_EOPERATION_ENTERREGIONS_TRANSITIONACTIVATION_EVENTOCCURRENCE = 3457;
			static const int STATEACTIVATION_EOPERATION_GETCONNECTIONPOINTACTIVATION = 3454;
			static const int STATEACTIVATION_EOPERATION_GETCONNECTIONPOINTACTIVATION_VERTEX = 3455;
			static const int STATEACTIVATION_EOPERATION_GETDOACTIVITY = 3460;
			static const int STATEACTIVATION_EOPERATION_GETENTRY = 3458;
			static const int STATEACTIVATION_EOPERATION_GETEXIT = 3459;
			static const int STATEACTIVATION_EOPERATION_GETFIREABLETRANSITIONS_EVENTOCCURRENCE = 3456;
			static const int STATEACTIVATION_EOPERATION_GETREGIONACTIVATION = 3449;
			static const int STATEACTIVATION_EOPERATION_HASCOMPLETED = 3447;
			static const int STATEACTIVATION_EOPERATION_NOTIFYCOMPLETION = 3445;
			static const int STATEACTIVATION_EOPERATION_RELEASEDEFERREDEVENTS = 3446;
			static const int STATEACTIVATION_EOPERATION_TRYEXECUTEENTRY_EVENTOCCURRENCE = 3451;
			static const int STATEACTIVATION_EOPERATION_TRYEXECUTEEXIT_EVENTOCCURRENCE = 3450;
			static const int STATEACTIVATION_EOPERATION_TRYINVOKEDOACTIVITY_EVENTOCCURRENCE = 3453;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateActivation_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getStateActivation_EAttribute_isDoActivityCompleted() const = 0;
			virtual std::shared_ptr<ecore::EAttribute> getStateActivation_EAttribute_isEntryCompleted() const = 0;
			virtual std::shared_ptr<ecore::EAttribute> getStateActivation_EAttribute_isExitCompleted() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getStateActivation_EReference_connectionPointActivations() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateActivation_EReference_doActivityContextObject() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateActivation_EReference_regionActivations() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_canDefer_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_defer_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_enterRegions_TransitionActivation_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getConnectionPointActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getConnectionPointActivation_Vertex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getDoActivity() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getEntry() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getExit() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getFireableTransitions_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_getRegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_hasCompleted() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_notifyCompletion() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_releaseDeferredEvents() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_tryExecuteEntry_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_tryExecuteExit_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateActivation_EOperation_tryInvokeDoActivity_EventOccurrence() const = 0;
			
			// End Class StateActivation


			// Begin Class StateConfiguration
			//Class and Feature IDs 
			static const unsigned int STATECONFIGURATION_ECLASS = 35;
			static const unsigned int STATECONFIGURATION_ECLASS_FEATURE_COUNT = 4;
			static const unsigned int STATECONFIGURATION_ECLASS_OPERATION_COUNT = 11;
			static const int STATECONFIGURATION_EATTRIBUTE_LEVEL = 3500;
			
			static const int STATECONFIGURATION_EREFERENCE_CHILDREN = 3502;
			static const int STATECONFIGURATION_EREFERENCE_COMPLETECONFIGURATION = 3503;
			static const int STATECONFIGURATION_EREFERENCE_VERTEXACTIVATION = 3501;
			
			static const int STATECONFIGURATION_EOPERATION_ADD_VERTEXACTIVATION_VERTEXACTIVATION = 3513;
			static const int STATECONFIGURATION_EOPERATION_ADDCHILD_VERTEXACTIVATION = 3512;
			static const int STATECONFIGURATION_EOPERATION_GETCHILDREN = 3505;
			static const int STATECONFIGURATION_EOPERATION_GETCONTEXT_VERTEXACTIVATION = 3509;
			static const int STATECONFIGURATION_EOPERATION_GETLEVEL = 3504;
			static const int STATECONFIGURATION_EOPERATION_GETPARENT = 3506;
			static const int STATECONFIGURATION_EOPERATION_GETVERTEXACTIVATION = 3507;
			static const int STATECONFIGURATION_EOPERATION_ISACTIVE = 3514;
			static const int STATECONFIGURATION_EOPERATION_REMOVE_VERTEXACTIVATION_VERTEXACTIVATION = 3511;
			static const int STATECONFIGURATION_EOPERATION_REMOVECHILD_VERTEXACTIVATION = 3510;
			static const int STATECONFIGURATION_EOPERATION_SETPARENT_STATECONFIGURATION = 3508;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateConfiguration_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getStateConfiguration_EAttribute_level() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getStateConfiguration_EReference_children() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateConfiguration_EReference_completeConfiguration() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateConfiguration_EReference_vertexActivation() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_add_VertexActivation_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_addChild_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_getChildren() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_getContext_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_getLevel() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_getParent() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_getVertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_isActive() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_remove_VertexActivation_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_removeChild_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateConfiguration_EOperation_setParent_StateConfiguration() const = 0;
			
			// End Class StateConfiguration


			// Begin Class StateMachineConfiguration
			//Class and Feature IDs 
			static const unsigned int STATEMACHINECONFIGURATION_ECLASS = 36;
			static const unsigned int STATEMACHINECONFIGURATION_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int STATEMACHINECONFIGURATION_ECLASS_OPERATION_COUNT = 9;
			
			static const int STATEMACHINECONFIGURATION_EREFERENCE_EXECUTION = 3601;
			static const int STATEMACHINECONFIGURATION_EREFERENCE_ROOTCONFIGURATION = 3600;
			
			static const int STATEMACHINECONFIGURATION_EOPERATION__REGISTER_STATEACTIVATION = 3605;
			static const int STATEMACHINECONFIGURATION_EOPERATION_ADD_VERTEXACTIVATION = 3610;
			static const int STATEMACHINECONFIGURATION_EOPERATION_GETEXECUTION = 3603;
			static const int STATEMACHINECONFIGURATION_EOPERATION_GETROOT = 3602;
			static const int STATEMACHINECONFIGURATION_EOPERATION_GETVERTEXACTIVATIONSATLEVEL_INTEGER = 3604;
			static const int STATEMACHINECONFIGURATION_EOPERATION_ISACTIVE_VERTEXACTIVATION = 3608;
			static const int STATEMACHINECONFIGURATION_EOPERATION_ISSTABLE = 3607;
			static const int STATEMACHINECONFIGURATION_EOPERATION_REMOVE_VERTEXACTIVATION = 3609;
			static const int STATEMACHINECONFIGURATION_EOPERATION_UNREGISTER_STATEACTIVATION = 3606;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateMachineConfiguration_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getStateMachineConfiguration_EReference_execution() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateMachineConfiguration_EReference_rootConfiguration() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation__register_StateActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_add_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_getExecution() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_getRoot() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_getVertexActivationsAtLevel_Integer() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_isActive_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_isStable() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_remove_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineConfiguration_EOperation_unregister_StateActivation() const = 0;
			
			// End Class StateMachineConfiguration


			// Begin Class StateMachineEventAccepter
			//Class and Feature IDs 
			static const unsigned int STATEMACHINEEVENTACCEPTER_ECLASS = 37;
			static const unsigned int STATEMACHINEEVENTACCEPTER_ECLASS_FEATURE_COUNT = 1;
			static const unsigned int STATEMACHINEEVENTACCEPTER_ECLASS_OPERATION_COUNT = 9;
			
			static const int STATEMACHINEEVENTACCEPTER_EREFERENCE_REGISTRATIONCONTEXT = 3700;
			
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION__DEFER_EVENTOCCURRENCE_STATECONFIGURATION = 3708;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION__ISDEFERRED_EVENTOCCURRENCE_STATECONFIGURATION = 3706;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION__SELECT_EVENTOCCURRENCE_STATECONFIGURATION = 3704;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_ACCEPT_EVENTOCCURRENCE = 3702;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_DEFER_EVENTOCCURRENCE = 3707;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_ISDEFERRED_EVENTOCCURRENCE = 3705;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_ISTRIGGERING_EVENTOCCURRENCE = 3709;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_MATCH_EVENTOCCURRENCE = 3701;
			static const int STATEMACHINEEVENTACCEPTER_EOPERATION_SELECT_EVENTOCCURRENCE = 3703;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateMachineEventAccepter_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getStateMachineEventAccepter_EReference_registrationContext() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation__defer_EventOccurrence_StateConfiguration() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation__isDeferred_EventOccurrence_StateConfiguration() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation__select_EventOccurrence_StateConfiguration() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_accept_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_defer_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_isDeferred_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_isTriggering_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_match_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineEventAccepter_EOperation_select_EventOccurrence() const = 0;
			
			// End Class StateMachineEventAccepter


			// Begin Class StateMachineExecution
			//Class and Feature IDs 
			static const unsigned int STATEMACHINEEXECUTION_ECLASS = 38;
			static const unsigned int STATEMACHINEEXECUTION_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int STATEMACHINEEXECUTION_ECLASS_OPERATION_COUNT = 8;
			
			static const int STATEMACHINEEXECUTION_EREFERENCE_CONFIGURATION = 3801;
			static const int STATEMACHINEEXECUTION_EREFERENCE_REGIONACTIVATIONS = 3800;
			
			static const int STATEMACHINEEXECUTION_EOPERATION_EXECUTE = 3802;
			static const int STATEMACHINEEXECUTION_EOPERATION_GETCONFIGURATION = 3805;
			static const int STATEMACHINEEXECUTION_EOPERATION_GETREGIONACTIVATION = 3807;
			static const int STATEMACHINEEXECUTION_EOPERATION_GETVERTEXACTIVATION_VERTEX = 3806;
			static const int STATEMACHINEEXECUTION_EOPERATION_INITREGIONS = 3804;
			static const int STATEMACHINEEXECUTION_EOPERATION_NEW_ = 3803;
			static const int STATEMACHINEEXECUTION_EOPERATION_STARTBEHAVIOR_CLASS_PARAMETERVALUE = 3809;
			static const int STATEMACHINEEXECUTION_EOPERATION_TERMINATE = 3808;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateMachineExecution_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getStateMachineExecution_EReference_configuration() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateMachineExecution_EReference_regionActivations() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_execute() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_getConfiguration() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_getRegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_getVertexActivation_Vertex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_initRegions() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_new_() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_startBehavior_Class_ParameterValue() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineExecution_EOperation_terminate() const = 0;
			
			// End Class StateMachineExecution


			// Begin Class StateMachineSemanticVisitor
			//Class and Feature IDs 
			static const unsigned int STATEMACHINESEMANTICVISITOR_ECLASS = 39;
			static const unsigned int STATEMACHINESEMANTICVISITOR_ECLASS_FEATURE_COUNT = 2;
			static const unsigned int STATEMACHINESEMANTICVISITOR_ECLASS_OPERATION_COUNT = 13;
			
			static const int STATEMACHINESEMANTICVISITOR_EREFERENCE_NODE = 3900;
			static const int STATEMACHINESEMANTICVISITOR_EREFERENCE_PARENT = 3901;
			
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_ACTIVATE = 3902;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_ACTIVATETRANSITIONS = 3903;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETCONTEXTCHAIN = 3911;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETEXECUTIONCONTEXT = 3907;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETEXECUTIONFOR_BEHAVIOR_EVENTOCCURRENCE = 3914;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETEXECUTIONLOCUS = 3905;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETNODE = 3904;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETPARENT = 3906;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_GETSTATEMACHINEEXECUTION = 3910;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_ISVISITORFOR_NAMEDELEMENT = 3912;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_MATCH_EVENTOCCURRENCE_TRIGGER = 3913;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_SETNODE_NAMEDELEMENT = 3909;
			static const int STATEMACHINESEMANTICVISITOR_EOPERATION_SETPARENT_EJAVAOBJECT = 3908;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getStateMachineSemanticVisitor_EClass() const = 0;
			
			
			virtual std::shared_ptr<ecore::EReference> getStateMachineSemanticVisitor_EReference_node() const = 0;
			virtual std::shared_ptr<ecore::EReference> getStateMachineSemanticVisitor_EReference_parent() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_activate() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_activateTransitions() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getContextChain() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getExecutionContext() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getExecutionFor_Behavior_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getExecutionLocus() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getNode() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getParent() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_getStateMachineExecution() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_isVisitorFor_NamedElement() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_match_EventOccurrence_Trigger() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_setNode_NamedElement() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getStateMachineSemanticVisitor_EOperation_setParent_EJavaObject() const = 0;
			
			// End Class StateMachineSemanticVisitor


			// Begin Class TerminatePseudostateActivation
			//Class and Feature IDs 
			static const unsigned int TERMINATEPSEUDOSTATEACTIVATION_ECLASS = 41;
			static const unsigned int TERMINATEPSEUDOSTATEACTIVATION_ECLASS_FEATURE_COUNT = 6;
			static const unsigned int TERMINATEPSEUDOSTATEACTIVATION_ECLASS_OPERATION_COUNT = 35;
			
			
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getTerminatePseudostateActivation_EClass() const = 0;
			
			
			
			
			// End Class TerminatePseudostateActivation


			// Begin Class TransitionActivation
			//Class and Feature IDs 
			static const unsigned int TRANSITIONACTIVATION_ECLASS = 42;
			static const unsigned int TRANSITIONACTIVATION_ECLASS_FEATURE_COUNT = 9;
			static const unsigned int TRANSITIONACTIVATION_ECLASS_OPERATION_COUNT = 32;
			static const int TRANSITIONACTIVATION_EATTRIBUTE_ANALYTICALSTATUS = 4205;
			static const int TRANSITIONACTIVATION_EATTRIBUTE_LASTPROPAGATION = 4206;
			static const int TRANSITIONACTIVATION_EATTRIBUTE_STATUS = 4202;
			
			static const int TRANSITIONACTIVATION_EREFERENCE_LASTTRIGGERINGEVENTOCCURRENCE = 4208;
			static const int TRANSITIONACTIVATION_EREFERENCE_LEASTCOMMONANCESTOR = 4207;
			static const int TRANSITIONACTIVATION_EREFERENCE_SOURCEVERTEXACTIVATION = 4203;
			static const int TRANSITIONACTIVATION_EREFERENCE_TARGETVERTEXACTIVATION = 4204;
			
			static const int TRANSITIONACTIVATION_EOPERATION_CANFIREON_EVENTOCCURRENCE = 4237;
			static const int TRANSITIONACTIVATION_EOPERATION_CANPROPAGATEEXECUTION_EVENTOCCURRENCE = 4240;
			static const int TRANSITIONACTIVATION_EOPERATION_ENTERTARGET_EVENTOCCURRENCE = 4233;
			static const int TRANSITIONACTIVATION_EOPERATION_EVALUATEGUARD_EVENTOCCURRENCE = 4239;
			static const int TRANSITIONACTIVATION_EOPERATION_EXITSOURCE_EVENTOCCURRENCE = 4231;
			static const int TRANSITIONACTIVATION_EOPERATION_FIRE_EVENTOCCURRENCE = 4228;
			static const int TRANSITIONACTIVATION_EOPERATION_GETLEASTCOMMONANCESTOR = 4232;
			static const int TRANSITIONACTIVATION_EOPERATION_GETSOURCEACTIVATION = 4226;
			static const int TRANSITIONACTIVATION_EOPERATION_GETSTATUS = 4224;
			static const int TRANSITIONACTIVATION_EOPERATION_GETTARGETACTIVATION = 4227;
			static const int TRANSITIONACTIVATION_EOPERATION_HASTRIGGER_EVENTOCCURRENCE = 4238;
			static const int TRANSITIONACTIVATION_EOPERATION_ISGUARDED = 4223;
			static const int TRANSITIONACTIVATION_EOPERATION_ISREACHED = 4222;
			static const int TRANSITIONACTIVATION_EOPERATION_ISTRAVERSED_BOOLEAN = 4229;
			static const int TRANSITIONACTIVATION_EOPERATION_ISTRIGGERED_BOOLEAN = 4230;
			static const int TRANSITIONACTIVATION_EOPERATION_SETSOURCEACTIVATION_VERTEXACTIVATION = 4235;
			static const int TRANSITIONACTIVATION_EOPERATION_SETSTATUS_TRANSITIONMETADATA = 4225;
			static const int TRANSITIONACTIVATION_EOPERATION_SETTARGETACTIVATION_VERTEXACTIVATION = 4236;
			static const int TRANSITIONACTIVATION_EOPERATION_TRYEXECUTEEFFECT_EVENTOCCURRENCE = 4234;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getTransitionActivation_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getTransitionActivation_EAttribute_analyticalStatus() const = 0;
			virtual std::shared_ptr<ecore::EAttribute> getTransitionActivation_EAttribute_lastPropagation() const = 0;
			virtual std::shared_ptr<ecore::EAttribute> getTransitionActivation_EAttribute_status() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getTransitionActivation_EReference_lastTriggeringEventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EReference> getTransitionActivation_EReference_leastCommonAncestor() const = 0;
			virtual std::shared_ptr<ecore::EReference> getTransitionActivation_EReference_sourceVertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EReference> getTransitionActivation_EReference_targetVertexActivation() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_canFireOn_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_canPropagateExecution_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_enterTarget_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_evaluateGuard_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_exitSource_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_fire_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_getLeastCommonAncestor() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_getSourceActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_getStatus() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_getTargetActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_hasTrigger_EventOccurrence() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_isGuarded() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_isReached() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_isTraversed_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_isTriggered_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_setSourceActivation_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_setStatus_TransitionMetadata() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_setTargetActivation_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getTransitionActivation_EOperation_tryExecuteEffect_EventOccurrence() const = 0;
			
			// End Class TransitionActivation


			// Begin Class VertexActivation
			//Class and Feature IDs 
			static const unsigned int VERTEXACTIVATION_ECLASS = 44;
			static const unsigned int VERTEXACTIVATION_ECLASS_FEATURE_COUNT = 5;
			static const unsigned int VERTEXACTIVATION_ECLASS_OPERATION_COUNT = 34;
			static const int VERTEXACTIVATION_EATTRIBUTE_STATUS = 4402;
			
			static const int VERTEXACTIVATION_EREFERENCE_INCOMINGTRANSITIONACTIVATIONS = 4403;
			static const int VERTEXACTIVATION_EREFERENCE_OUTGOINGTRANSITIONACTIVATIONS = 4404;
			
			static const int VERTEXACTIVATION_EOPERATION_ADDINCOMINGTRANSITION_TRANSITIONACTIVATION = 4428;
			static const int VERTEXACTIVATION_EOPERATION_ADDOUTGOINGTRANSITION_TRANSITIONACTIVATION = 4429;
			static const int VERTEXACTIVATION_EOPERATION_CANPROPAGATEEXECUTION_TRANSITIONACTIVATION_REGIONACTIVATION = 4437;
			static const int VERTEXACTIVATION_EOPERATION_ENTER_TRANSITIONACTIVATION_REGIONACTIVATION = 4436;
			static const int VERTEXACTIVATION_EOPERATION_EXIT_TRANSITIONACTIVATION_REGIONACTIVATION = 4435;
			static const int VERTEXACTIVATION_EOPERATION_GETASCENDINGHIERARCHY = 4423;
			static const int VERTEXACTIVATION_EOPERATION_GETINCOMINGTRANSITIONS = 4425;
			static const int VERTEXACTIVATION_EOPERATION_GETLEASTCOMMONANCESTOR_VERTEXACTIVATION = 4432;
			static const int VERTEXACTIVATION_EOPERATION_GETOUTGOINGTRANSITIONS = 4426;
			static const int VERTEXACTIVATION_EOPERATION_GETOWNINGREGIONACTIVATION = 4424;
			static const int VERTEXACTIVATION_EOPERATION_GETPARENTVERTEXACTIVATION = 4422;
			static const int VERTEXACTIVATION_EOPERATION_GETREGIONACTIVATION_SEMANTICVISITOR = 4438;
			static const int VERTEXACTIVATION_EOPERATION_GETSTATUS = 4420;
			static const int VERTEXACTIVATION_EOPERATION_GETVERTEXACTIVATION_VERTEX = 4427;
			static const int VERTEXACTIVATION_EOPERATION_ISACTIVE = 4419;
			static const int VERTEXACTIVATION_EOPERATION_ISENTERABLE_TRANSITIONACTIVATION_BOOLEAN = 4434;
			static const int VERTEXACTIVATION_EOPERATION_ISEXITABLE_TRANSITIONACTIVATION_BOOLEAN = 4433;
			static const int VERTEXACTIVATION_EOPERATION_SETSTATUS_STATEMETADATA = 4421;
			static const int VERTEXACTIVATION_EOPERATION_TAGINCOMINGTRANSITION_TRANSITIONMETADATA_BOOLEAN = 4431;
			static const int VERTEXACTIVATION_EOPERATION_TAGOUTGOINGTRANSITION_TRANSITIONMETADATA_BOOLEAN = 4430;
			static const int VERTEXACTIVATION_EOPERATION_TERMINATE = 4418;
			
			//Class and Feature Getter
			virtual std::shared_ptr<ecore::EClass> getVertexActivation_EClass() const = 0;
			
			virtual std::shared_ptr<ecore::EAttribute> getVertexActivation_EAttribute_status() const = 0;
			
			virtual std::shared_ptr<ecore::EReference> getVertexActivation_EReference_incomingTransitionActivations() const = 0;
			virtual std::shared_ptr<ecore::EReference> getVertexActivation_EReference_outgoingTransitionActivations() const = 0;
			
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_addIncomingTransition_TransitionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_addOutgoingTransition_TransitionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_canPropagateExecution_TransitionActivation_RegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_enter_TransitionActivation_RegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_exit_TransitionActivation_RegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getAscendingHierarchy() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getIncomingTransitions() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getLeastCommonAncestor_VertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getOutgoingTransitions() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getOwningRegionActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getParentVertexActivation() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getRegionActivation_SemanticVisitor() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getStatus() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_getVertexActivation_Vertex() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_isActive() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_isEnterable_TransitionActivation_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_isExitable_TransitionActivation_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_setStatus_StateMetadata() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_tagIncomingTransition_TransitionMetadata_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_tagOutgoingTransition_TransitionMetadata_Boolean() const = 0;
			virtual std::shared_ptr<ecore::EOperation> getVertexActivation_EOperation_terminate() const = 0;
			
			// End Class VertexActivation

			static const int STATEMETADATA_EENUM = 40;
			static const int TRANSITIONMETADATA_EENUM = 43;
			
			virtual std::shared_ptr<ecore::EEnum> getStateMetadata_EEnum() const = 0;
			virtual std::shared_ptr<ecore::EEnum> getTransitionMetadata_EEnum() const = 0;
			

			//Singleton Instance and Getter
			private:
				static std::shared_ptr<PSSMPackage> instance;
			public:
				static std::shared_ptr<PSSMPackage> eInstance();
	};
}
#endif /* end of include guard: PSSMPACKAGE_HPP */
