//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCE_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCE_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace fUML 
{
	class EventOccurrence;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateActivation;
}

// base class includes
#include "fUML/EventOccurrence.hpp"

// enum includes


//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class DeferredEventOccurrence:virtual public fUML::EventOccurrence
	{
		public:
 			DeferredEventOccurrence(const DeferredEventOccurrence &) {}
			DeferredEventOccurrence& operator=(DeferredEventOccurrence const&) = delete;

		protected:
			DeferredEventOccurrence(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~DeferredEventOccurrence() {}

			//*********************************
			// Operations
			//*********************************
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getConstrainingStateActivation() const = 0;
			
			/*!
			 */
			virtual void setConstrainingStateActivation(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _constrainingStateActivation_constrainingStateActivation) = 0;
			/*!
			 */
			virtual std::shared_ptr<fUML::EventOccurrence > getDeferredEventOccurrence() const = 0;
			
			/*!
			 */
			virtual void setDeferredEventOccurrence(std::shared_ptr<fUML::EventOccurrence> _deferredEventOccurrence_deferredEventOccurrence) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > m_constrainingStateActivation;
			/*!
			 */
			std::shared_ptr<fUML::EventOccurrence > m_deferredEventOccurrence;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DEFERREDEVENTOCCURRENCE_HPP */
