//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTER_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTER_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace PSSM::Semantics::StateMachines 
{
	class DoActivityContextObject;
}

namespace fUML 
{
	class EventAccepter;
}

namespace fUML 
{
	class EventOccurrence;
}

// base class includes

// enum includes

#include "ecore/EObject.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class DoActivityExecutionEventAccepter : virtual public ecore::EObject 

	{
		public:
 			DoActivityExecutionEventAccepter(const DoActivityExecutionEventAccepter &) {}
			DoActivityExecutionEventAccepter& operator=(DoActivityExecutionEventAccepter const&) = delete;

		protected:
			DoActivityExecutionEventAccepter(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~DoActivityExecutionEventAccepter() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void accept(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual bool match(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject > getContext() const = 0;
			
			/*!
			 */
			virtual void setContext(std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject> _context_context) = 0;
			/*!
			 */
			virtual std::shared_ptr<fUML::EventAccepter > getEncapsulatedAccepter() const = 0;
			
			/*!
			 */
			virtual void setEncapsulatedAccepter(std::shared_ptr<fUML::EventAccepter> _encapsulatedAccepter_encapsulatedAccepter) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::DoActivityContextObject > m_context;
			/*!
			 */
			std::shared_ptr<fUML::EventAccepter > m_encapsulatedAccepter;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYEXECUTIONEVENTACCEPTER_HPP */
