//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECT_HPP
#define PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECT_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace uml 
{
	class Class;
}

namespace fUML 
{
	class EventAccepter;
}

namespace fUML 
{
	class EventOccurrence;
}

namespace fUML 
{
	class Execution;
}

namespace fUML 
{
	class FeatureValue;
}

namespace fUML 
{
	class Object;
}

namespace uml 
{
	class Operation;
}

namespace fUML 
{
	class ParameterValue;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateActivation;
}

namespace uml 
{
	class StructuralFeature;
}

namespace fUML 
{
	class Value;
}

// base class includes

// enum includes

#include "ecore/EObject.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class DoActivityContextObject : virtual public ecore::EObject 

	{
		public:
 			DoActivityContextObject(const DoActivityContextObject &) {}
			DoActivityContextObject& operator=(DoActivityContextObject const&) = delete;

		protected:
			DoActivityContextObject(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~DoActivityContextObject() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void _register(std::shared_ptr<fUML::EventAccepter>  accepter) = 0;
			
			/*!
			 */ 
			virtual void destroy() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<fUML::Execution> dispatch(std::shared_ptr<uml::Operation>  operation) = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<fUML::FeatureValue> getFeatureValue(std::shared_ptr<uml::StructuralFeature>  feature) = 0;
			
			/*!
			 */ 
			virtual void initialize(std::shared_ptr<fUML::Object>  context) = 0;
			
			/*!
			 */ 
			virtual void send(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual void setFeatureValue(std::shared_ptr<uml::StructuralFeature>  feature,std::shared_ptr<Bag<fUML::Value> >  values,int position) = 0;
			
			/*!
			 */ 
			virtual void startBehavior(std::shared_ptr<uml::Class>  classifier,std::shared_ptr<Bag<fUML::ParameterValue> >  inputs) = 0;
			
			/*!
			 */ 
			virtual void unregister(std::shared_ptr<fUML::EventAccepter>  accepter) = 0;
			
			/*!
			 */ 
			virtual void unregisterFromContext(std::shared_ptr<fUML::EventAccepter>  encapsulatedAccepter) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<fUML::Object > getContext() const = 0;
			
			/*!
			 */
			virtual void setContext(std::shared_ptr<fUML::Object> _context_context) = 0;
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getOwner() const = 0;
			
			/*!
			 */
			virtual void setOwner(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _owner_owner) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<fUML::Object > m_context;
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > m_owner;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_DOACTIVITYCONTEXTOBJECT_HPP */
