//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_HISTORYPSEUDOSTATEACTIVATION_HPP
#define PSSM_SEMANTICS_STATEMACHINES_HISTORYPSEUDOSTATEACTIVATION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace fUML 
{
	class EventOccurrence;
}

namespace uml 
{
	class NamedElement;
}

namespace PSSM::Semantics::StateMachines 
{
	class PseudostateActivation;
}

namespace PSSM::Semantics::StateMachines 
{
	class RegionActivation;
}

namespace fUML 
{
	class SemanticVisitor;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateActivation;
}

namespace PSSM::Semantics::StateMachines 
{
	class TransitionActivation;
}

// base class includes
#include "PSSM/Semantics/StateMachines/PseudostateActivation.hpp"

// enum includes
#include "PSSM/Semantics/StateMachines/StateMetadata.hpp"


//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class HistoryPseudostateActivation:virtual public PseudostateActivation
	{
		public:
 			HistoryPseudostateActivation(const HistoryPseudostateActivation &) {}
			HistoryPseudostateActivation& operator=(HistoryPseudostateActivation const&) = delete;

		protected:
			HistoryPseudostateActivation(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~HistoryPseudostateActivation() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual bool hasDefaultTransition() = 0;
			
			/*!
			 */ 
			virtual void restore(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation>  stateActivation,std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual void restore(std::shared_ptr<PSSM::Semantics::StateMachines::RegionActivation>  regionActivation,std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_HISTORYPSEUDOSTATEACTIVATION_HPP */
