//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_PSEUDOSTATEACTIVATION_HPP
#define PSSM_SEMANTICS_STATEMACHINES_PSEUDOSTATEACTIVATION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace fUML 
{
	class EventOccurrence;
}

namespace uml 
{
	class NamedElement;
}

namespace fUML 
{
	class SemanticVisitor;
}

namespace PSSM::Semantics::StateMachines 
{
	class TransitionActivation;
}

namespace PSSM::Semantics::StateMachines 
{
	class VertexActivation;
}

// base class includes
#include "PSSM/Semantics/StateMachines/VertexActivation.hpp"

// enum includes
#include "PSSM/Semantics/StateMachines/StateMetadata.hpp"


//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class PseudostateActivation:virtual public VertexActivation
	{
		public:
 			PseudostateActivation(const PseudostateActivation &) {}
			PseudostateActivation& operator=(PseudostateActivation const&) = delete;

		protected:
			PseudostateActivation(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~PseudostateActivation() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void evaluateAllGuards(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation>> getFireableTransitions() const = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation>> m_fireableTransitions;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_PSEUDOSTATEACTIVATION_HPP */
