//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATION_HPP
#define PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace fUML 
{
	class EventOccurrence;
}

namespace PSSM::Semantics::StateMachines 
{
	class InitialPseudostateActivation;
}

namespace uml 
{
	class NamedElement;
}

namespace fUML 
{
	class SemanticVisitor;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateActivation;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateMachineSemanticVisitor;
}

namespace uml 
{
	class Transition;
}

namespace PSSM::Semantics::StateMachines 
{
	class TransitionActivation;
}

namespace uml 
{
	class Vertex;
}

namespace PSSM::Semantics::StateMachines 
{
	class VertexActivation;
}

// base class includes
#include "PSSM/Semantics/StateMachines/StateMachineSemanticVisitor.hpp"

// enum includes


//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class RegionActivation:virtual public StateMachineSemanticVisitor
	{
		public:
 			RegionActivation(const RegionActivation &) {}
			RegionActivation& operator=(RegionActivation const&) = delete;

		protected:
			RegionActivation(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~RegionActivation() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual bool canPropagateExecution(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual void enter(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  enteringTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual void exit(std::shared_ptr<PSSM::Semantics::StateMachines::TransitionActivation>  exitingTransition,std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::InitialPseudostateActivation> getOrigin() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation> > getTransitionActivations() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation> getVertexActivation(std::shared_ptr<uml::Vertex>  vertex) = 0;
			
			
			
			/*!
			 */ 
			virtual bool isRedefined(std::shared_ptr<Bag<uml::Vertex> >  vertices,std::shared_ptr<uml::Vertex>  vertex) = 0;
			
			/*!
			 */ 
			virtual bool isRedefined(std::shared_ptr<Bag<uml::Transition> >  transitions,std::shared_ptr<uml::Transition>  transition) = 0;
			
			/*!
			 */ 
			virtual void terminate() = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			/*!
			 */ 
			virtual bool getIsCompleted() const = 0;
			
			/*!
			 */ 
			virtual void setIsCompleted (bool _isCompleted)= 0; 
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > getHistory() const = 0;
			
			/*!
			 */
			virtual void setHistory(std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation> _history_history) = 0;
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation>> getTransitionActivations() const = 0;
			
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation>> getVertexActivations() const = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			/*!
			 */ 
			bool m_isCompleted = false;
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::StateActivation > m_history;
			/*!
			 */
			std::shared_ptr<Bag<PSSM::Semantics::StateMachines::TransitionActivation>> m_transitionActivations;
			/*!
			 */
			std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation>> m_vertexActivations;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_REGIONACTIVATION_HPP */
