//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_STATECONFIGURATION_HPP
#define PSSM_SEMANTICS_STATEMACHINES_STATECONFIGURATION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace PSSM::Semantics::StateMachines 
{
	class StateConfiguration;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateMachineConfiguration;
}

namespace PSSM::Semantics::StateMachines 
{
	class VertexActivation;
}

// base class includes

// enum includes

#include "ecore/EObject.hpp"

//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class StateConfiguration : virtual public ecore::EObject 

	{
		public:
 			StateConfiguration(const StateConfiguration &) {}
			StateConfiguration& operator=(StateConfiguration const&) = delete;

		protected:
			StateConfiguration(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~StateConfiguration() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual void add(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation,std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation> >  context) = 0;
			
			/*!
			 */ 
			virtual void addChild(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation) = 0;
			
			
			
			/*!
			 */ 
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation> > getContext(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation) = 0;
			
			/*!
			 */ 
			virtual int getLevel() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration> getParent() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation> getVertexActivation() = 0;
			
			/*!
			 */ 
			virtual bool isActive() = 0;
			
			/*!
			 */ 
			virtual void remove(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation,std::shared_ptr<Bag<PSSM::Semantics::StateMachines::VertexActivation> >  context) = 0;
			
			/*!
			 */ 
			virtual void removeChild(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation>  activation) = 0;
			
			/*!
			 */ 
			virtual void setParent(std::shared_ptr<PSSM::Semantics::StateMachines::StateConfiguration>  stateConfiguration) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			/*!
			 */ 
			virtual int getLevel() const = 0;
			
			/*!
			 */ 
			virtual void setLevel (int _level)= 0; 
			
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::StateConfiguration>> getChildren() const = 0;
			
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration > getCompleteConfiguration() const = 0;
			
			/*!
			 */
			virtual void setCompleteConfiguration(std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> _completeConfiguration_completeConfiguration) = 0;
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation > getVertexActivation() const = 0;
			
			/*!
			 */
			virtual void setVertexActivation(std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation> _vertexActivation_vertexActivation) = 0;
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			/*!
			 */ 
			int m_level = 0;
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<Bag<PSSM::Semantics::StateMachines::StateConfiguration>> m_children;
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration > m_completeConfiguration;
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation > m_vertexActivation;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_STATECONFIGURATION_HPP */
