//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_STATEMACHINES_STATEMACHINEEXECUTION_HPP
#define PSSM_SEMANTICS_STATEMACHINES_STATEMACHINEEXECUTION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace uml 
{
	class Class;
}

namespace uml 
{
	class Classifier;
}

namespace fUML 
{
	class Execution;
}

namespace fUML 
{
	class FeatureValue;
}

namespace fUML 
{
	class Locus;
}

namespace fUML 
{
	class Object;
}

namespace fUML 
{
	class ObjectActivation;
}

namespace fUML 
{
	class ParameterValue;
}

namespace PSSM::Semantics::StateMachines 
{
	class RegionActivation;
}

namespace PSSM::Semantics::StateMachines 
{
	class StateMachineConfiguration;
}

namespace fUML 
{
	class Value;
}

namespace uml 
{
	class Vertex;
}

namespace PSSM::Semantics::StateMachines 
{
	class VertexActivation;
}

// base class includes
#include "fUML/Execution.hpp"

// enum includes


//*********************************
namespace PSSM::Semantics::StateMachines 
{
	/*!
	 */
	class StateMachineExecution:virtual public fUML::Execution
	{
		public:
 			StateMachineExecution(const StateMachineExecution &) {}
			StateMachineExecution& operator=(StateMachineExecution const&) = delete;

		protected:
			StateMachineExecution(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~StateMachineExecution() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 Execute the behavior given by the type of this execution. 
			The parameterValues for any input (in or in-out) parameters of the behavior should be set before the execution.
			The parameteValues for any output (in-out, out or return) parameters of the behavior will be set by the execution.
			 */ 
			virtual void execute() = 0;
			
			
			
			/*!
			 */ 
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::RegionActivation> > getRegionActivation() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::VertexActivation> getVertexActivation(std::shared_ptr<uml::Vertex>  vertex) = 0;
			
			/*!
			 */ 
			virtual void initRegions() = 0;
			
			/*!
			 Create a new execution with no behavior or parameterValues.
			 */ 
			virtual std::shared_ptr<fUML::Value> new_() = 0;
			
			/*!
			 */ 
			virtual void startBehavior(std::shared_ptr<uml::Class>  classifier,std::shared_ptr<Bag<fUML::ParameterValue> >  inputs) = 0;
			
			/*!
			 */ 
			virtual void terminate() = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration > getConfiguration() const = 0;
			
			/*!
			 */
			virtual void setConfiguration(std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration> _configuration_configuration) = 0;
			/*!
			 */
			virtual std::shared_ptr<Bag<PSSM::Semantics::StateMachines::RegionActivation>> getRegionActivations() const = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<PSSM::Semantics::StateMachines::StateMachineConfiguration > m_configuration;
			/*!
			 */
			std::shared_ptr<Bag<PSSM::Semantics::StateMachines::RegionActivation>> m_regionActivations;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_STATEMACHINES_STATEMACHINEEXECUTION_HPP */
