//********************************************************************
//*    
//* Warning: This file was generated by ecore4CPP Generator
//*
//********************************************************************

#ifndef PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATION_HPP
#define PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATION_HPP

#include <list>
#include <memory>
#include <string>


// forward declarations
template<class T> class Bag;



//*********************************
// generated Includes

#include <map>

namespace persistence
{
	namespace interfaces
	{
		class XLoadHandler; // used for Persistence
		class XSaveHandler; // used for Persistence
	}
}

namespace PSSM
{
	class PSSMFactory;
}

//Forward Declaration for used types
namespace fUML 
{
	class EventOccurrence;
}

namespace fUML 
{
	class Object;
}

namespace uml 
{
	class Parameter;
}

namespace fUML 
{
	class ParameterValue;
}

namespace fUML 
{
	class Value;
}

// base class includes

// enum includes

#include "ecore/EObject.hpp"

//*********************************
namespace PSSM::Semantics::Values 
{
	/*!
	 */
	class SM_OpaqueExpressionEvaluation : virtual public ecore::EObject 

	{
		public:
 			SM_OpaqueExpressionEvaluation(const SM_OpaqueExpressionEvaluation &) {}
			SM_OpaqueExpressionEvaluation& operator=(SM_OpaqueExpressionEvaluation const&) = delete;

		protected:
			SM_OpaqueExpressionEvaluation(){}


		public:
			virtual std::shared_ptr<ecore::EObject> copy() const = 0;

			//destructor
			virtual ~SM_OpaqueExpressionEvaluation() {}

			//*********************************
			// Operations
			//*********************************
			/*!
			 */ 
			virtual std::shared_ptr<Bag<fUML::Value> > executeExpressionBehavior() = 0;
			
			/*!
			 */ 
			virtual std::shared_ptr<fUML::ParameterValue> getParameterValue(std::shared_ptr<uml::Parameter>  parameter) = 0;
			
			/*!
			 */ 
			virtual void initialize(std::shared_ptr<fUML::EventOccurrence>  eventOccurrence) = 0;
			
			/*!
			 */ 
			virtual void setParameterValue(std::shared_ptr<fUML::ParameterValue>  parameterValue) = 0;
			
			
			//*********************************
			// Attributes Getter Setter
			//*********************************
			
			//*********************************
			// Reference
			//*********************************
			/*!
			 */
			virtual std::shared_ptr<fUML::Object > getContext() const = 0;
			
			/*!
			 */
			virtual void setContext(std::shared_ptr<fUML::Object> _context_context) = 0;
			/*!
			 */
			virtual std::shared_ptr<Bag<fUML::ParameterValue>> getParameterValues() const = 0;
			
			

		protected:
			//*********************************
			// Attribute Members
			//*********************************
			
			
			//*********************************
			// Reference Members
			//*********************************
			/*!
			 */
			std::shared_ptr<fUML::Object > m_context;
			/*!
			 */
			std::shared_ptr<Bag<fUML::ParameterValue>> m_parameterValues;
			

		public:
			//*********************************
			// Union Getter
			//*********************************
			

			virtual std::shared_ptr<ecore::EObject> eContainer() const = 0; 
			
			//*********************************
			// Persistence Functions
			//*********************************
			virtual void load(std::shared_ptr<persistence::interfaces::XLoadHandler> loadHandler) = 0;
			
			virtual void resolveReferences(const int featureID, std::list<std::shared_ptr<ecore::EObject> > references) = 0;
			virtual void save(std::shared_ptr<persistence::interfaces::XSaveHandler> saveHandler) const = 0;
			
	};

}
#endif /* end of include guard: PSSM_SEMANTICS_VALUES_SM_OPAQUEEXPRESSIONEVALUATION_HPP */
